#ifndef __NetBuilderSigma_frame__
#define __NetBuilderSigma_frame__

/**
@file
Subclass of Sigma, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"
#include "NetBuilderDistributions_frame.h"

/** Implementing Sigma */
class NetBuilderSigma_frame : public Sigma
{
protected:
	// Handlers for Sigma events.
	void OnInitSigma( wxInitDialogEvent& event );
	void Ok_Button_Click( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderSigma_frame( wxWindow* parent );
};

#endif // __NetBuilderSigma_frame__
