#ifndef __NetBuilderDelays_frame__
#define __NetBuilderDelays_frame__

/**
@file
Subclass of delays_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "NetBuilderSummary_frame.h"

/** Implementing delays_frame */
class NetBuilderDelays_frame : public Delays_frame
{
protected:
	// Handlers for delays_frame events.
	void OnInitDelays( wxInitDialogEvent& event );
//	void OnCellClickDelays( wxGridEvent& event );
	//void Onbtn_delays_CancelClick( wxCommandEvent& event );
	void Onbtn_delays_OKClick( wxCommandEvent& event );
	
	
public:
	/** Constructor */
	NetBuilderDelays_frame( wxWindow* parent );
};

#endif // __NetBuilderDelays_frame__
