#ifndef __NetBuilderDistributions_frame__
#define __NetBuilderDistributions_frame__

/**
@file
Subclass of Distributions_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"
#include "NetBuilderSummary_frame.h"
#include "NetBuilderSigma_frame.h"
#include "NetBuilderMainFrame.h"


/** Implementing Distributions_frame */
class NetBuilderDistributions_frame : public Distributions_frame
{
protected:
	// Handlers for Distributions_frame events.
	void OnInitdist( wxInitDialogEvent& event );
	void OnCellClick( wxGridEvent& event );
	void Onbtn_dist_OKClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderDistributions_frame( wxWindow* parent );
};

#endif // __NetBuilderDistributions_frame__
