#ifndef __NetBuilderOptions_frame__
#define __NetBuilderOptions_frame__

/**
@file
Subclass of Options_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include <wx/textfile.h>
#include <wx/choice.h>
#include <wx/button.h>

/** Implementing Options_frame */
class NetBuilderOptions_frame : public Options_frame
{
protected:
	// Handlers for Options_frame events.
	void OnInitOptions( wxInitDialogEvent& event );
	void On_syn_choices_Selection( wxCommandEvent& event );
	void On_conn_choices_Selection( wxCommandEvent& event );
	void On_auto_choices_Selection( wxCommandEvent& event );
	void On_mult_choices_Selection( wxCommandEvent& event );
	void On_btn_options_OKClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderOptions_frame( wxDialog* parent );
};

#endif // __NetBuilderOptions_frame__
