#ifndef __NetBuilderModel_frame__
#define __NetBuilderModel_frame__

/**
@file
Subclass of Model_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"

/** Implementing Model_frame */
class NetBuilderModel_frame : public Model_frame
{
protected:
  
	wxStaticText* text_title;
	// Handlers for Model_frame events.
	void OnInitModel( wxInitDialogEvent& event );
	void Onbtn_Model_OKClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderModel_frame( wxDialog* parent );
	int line;
	int total_par;
};

#endif // __NetBuilderModel_frame__
