#ifndef __NetBuilderTopology_frame__
#define __NetBuilderTopology_frame__

/**
@file
Subclass of Topology_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"
#include "NetBuilderSummary_frame.h"


/** Implementing Topology_frame */
class NetBuilderTopology_frame : public Topology_frame
{
protected:
	// Handlers for Topology_frame events.
	void OnInitTopology( wxInitDialogEvent& event );
	void Onbtn_top_CancelClick( wxCommandEvent& event );
	void Onbtn_top_OKClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderTopology_frame( wxWindow* parent );
};

#endif // __NetBuilderTopology_frame__
