#ifndef __NetBuilderConnectivity_frame__
#define __NetBuilderConnectivity_frame__

/**
@file
Subclass of Connectivity_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"

#include <vector>
#include <wx/textfile.h>
#include <wx/choice.h>
#include "data_structures.h"
#include "NetBuilderSummary_frame.h"
#include "NetBuilderOptions_frame.h"

/** Implementing Connectivity_frame */
class NetBuilderConnectivity_frame : public Connectivity_frame
{
protected:
	// Handlers for Connectivity_frame events.
	void OnInitConnectivity( wxInitDialogEvent& event );
	void Onbtn_conn_OptionsClick( wxCommandEvent& event );
	void Onbtn_conn_OKClick( wxCommandEvent& event );
	
	
public:
	/** Constructor */
	NetBuilderConnectivity_frame( wxWindow* parent );
};

#endif // __NetBuilderConnectivity_frame__
