#ifndef __NetBuilderDynamics_frame__
#define __NetBuilderDynamics_frame__

/**
@file
Subclass of Dynamics_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "NetBuilderModel_frame.h"
#include "NetBuilderVisualization_frame.h"
#include "data_structures.h"
#include "FastComboEditor.h"
#include "GridCellChoiceRenderer.h"
#include "GridCellIconRenderer.h"
#include <vector>
#include <string>



/** Implementing Dynamics_frame */
class NetBuilderDynamics_frame : public Dynamics_frame
{
protected:
	// Handlers for Dynamics_frame events.
	void OnInitDynamics( wxInitDialogEvent& event );
	void OnCellClick( wxGridEvent& event );
	void Onbtn_Dynamics_OKClick( wxCommandEvent& event );
	void Onbtn_view_neuronClick( wxCommandEvent& event );
		
public:
	/** Constructor */
	
	NetBuilderDynamics_frame( wxDialog* parent );
};

#endif // __NetBuilderDynamics_frame__
