#ifndef __NetBuilderSummary_frame__
#define __NetBuilderSummary_frame__

/**
@file
Subclass of Summary_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"
#include <wx/font.h>
#include "wx/grid.h"
#include "wx/generic/gridctrl.h"
#include <wx/gdicmn.h>

/** Implementing Summary_frame */
class NetBuilderSummary_frame : public Summary_frame
{
protected:
	// Handlers for Summary_frame events.
	void OnCloseSummary( wxCloseEvent& event );
	void OnInitSummary( wxInitDialogEvent& event );
	
public:
	/** Constructor */
	NetBuilderSummary_frame( wxWindow* parent );
};

#endif // __NetBuilderSummary_frame__
