#ifndef __NetBuilderFdms_frame__
#define __NetBuilderFdms_frame__

/**
@file
Subclass of fdms_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "NetBuilderSummary_frame.h"

/** Implementing fdms_frame */
class NetBuilderFdms_frame : public Fdms_frame
{
protected:
	// Handlers for fdms_frame events.
	void OnInitFdms( wxInitDialogEvent& event );
	void OnCellClickFdms( wxGridEvent& event );
	//void Onbtn_fdms_CancelClick( wxCommandEvent& event );
	void Onbtn_fdms_OKClick( wxCommandEvent& event );
	
	
public:
	/** Constructor */
	NetBuilderFdms_frame( wxWindow* parent );
};

#endif // __NetBuilderFdms_frame__
