#ifndef __NetBuilderPlasticity_frame__
#define __NetBuilderPlasticity_frame__

/**
@file
Subclass of Plasticity_frame, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "data_structures.h"
#include "NetBuilderSummary_frame.h"
#include "data_structures.h"
#include "FastComboEditor.h"
#include "GridCellChoiceRenderer.h"
#include "GridCellIconRenderer.h"
#include "NetBuilderModel_frame.h"

/** Implementing Plasticity_frame */
class NetBuilderPlasticity_frame : public Plasticity_frame
{
protected:
	// Handlers for Plasticity_frame events.
	void OnInitPlasticity( wxInitDialogEvent& event );
	void OnCellClick( wxGridEvent& event );
	//void Onbtn_Plasticity_CancelClick( wxCommandEvent& event );
	void Onbtn_Plasticity_OKClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	NetBuilderPlasticity_frame( wxWindow* parent );
};

#endif // __NetBuilderPlasticity_frame__
