#ifndef __ElectrodeBuilder_ParametersFrame__
#define __ElectrodeBuilder_ParametersFrame__

/**
@file
Subclass of ParametersFrame, which is generated by wxFormBuilder.
*/

#include "Gui.h"
#include "ElectrodeBuilder_MainFrame.h"

/** Implementing ParametersFrame */
class ElectrodeBuilder_ParametersFrame : public ParametersFrame
{
protected:
	// Handlers for ParametersFrame events.

	void On_Init(wxInitDialogEvent& event );
	void On_Ok_Click( wxCommandEvent& event );
	
public:
	/** Constructor */
	ElectrodeBuilder_ParametersFrame( wxWindow* parent );
};

#endif // __ElectrodeBuilder_ParametersFrame__
