#ifndef __ElectrodeBuilder_MainFrame__
#define __ElectrodeBuilder_MainFrame__

/**
@file
Subclass of ElectrodeBuilder_MainFrame, which is generated by wxFormBuilder.
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wx/filename.h>
#include "Gui.h"
#include "ElectrodeBuilder_ParametersFrame.h"
#include "main.h"

/** Implementing MainFrame */
class ElectrodeBuilder_MainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void OnClose( wxCloseEvent& event );
	void On_Electrode_Change( wxCommandEvent& event );
	void On_Append_Click( wxCommandEvent& event );
	void On_Remove_Click( wxCommandEvent& event );
	void On_Finish_Click( wxCommandEvent& event );
	
public:
	/** Constructor */
	ElectrodeBuilder_MainFrame( wxWindow* parent );
};

#endif // __ElectrodeBuilder_MainFrame__
