//************************************************************************
//*                                                                      *
//*                     M O D E L S   L I B R A R Y                      *
//*                                                                      *
//************************************************************************

//                            I M P O R T A N T                           
//                            -----------------                           
// THIS FILE IS GENERATED AUTOMATICALLY USING DATA IN THE MODELS LIBRARIES
//    Do not edit this file. This file is generated by libgenerator.c     
// -----------------------------------------------------------------------


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "general.h"
#include "models.h"


//models
extern struct MODEL_DYNAMICS_NEURON *neuron_model;
extern struct MODEL_DYNAMICS_SYNAPSE *synapse_model;
extern struct MODEL_DYNAMICS_PLASTICITY *plasticity_model;



//------------------------------------------------------------------------
// Assign the appropriate function pointers to all models
void SetupModelsLibrary(void)
{
	int n_params, n_statevars;

	//allocate space for all models
	neuron_model = malloc( N_NEURON_MODELS * sizeof(struct MODEL_DYNAMICS_NEURON) );
	synapse_model = malloc( N_SYNAPSE_MODELS * sizeof(struct MODEL_DYNAMICS_SYNAPSE) );
	plasticity_model = malloc( N_PLASTICITY_MODELS * sizeof(struct MODEL_DYNAMICS_PLASTICITY) );


	//TAKE CARE OF NEURON MODELS
	//--------------------------

	// model_HH
	neuron_model[0].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].model_label, "HH");
	neuron_model[0].Initialize        = ModelInitialize_HH;
	neuron_model[0].Advance           = ModelAdvance_HH;
	n_params = 9;
	neuron_model[0].n_params          = 9;
	neuron_model[0].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[0].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[0], "Cm[nF]");
	neuron_model[0].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[1], "gL[uS]");
	neuron_model[0].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[2], "EL[mV]");
	neuron_model[0].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[3], "gNa_bar[uS]");
	neuron_model[0].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[4], "ENa[mV]");
	neuron_model[0].param_label[5]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[5], "gK_bar[uS]");
	neuron_model[0].param_label[6]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[6], "EK[mV]");
	neuron_model[0].param_label[7]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[7], "Temp[Celsius]");
	neuron_model[0].param_label[8]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].param_label[8], "VTraub[mV]");
	n_statevars = 3;
	neuron_model[0].n_statevars       = 3;
	neuron_model[0].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	neuron_model[0].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].statevar_label[0], "m[1]");
	neuron_model[0].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].statevar_label[1], "h[1]");
	neuron_model[0].statevar_label[2] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[0].statevar_label[2], "n[1]");

	// model_HH_O1
	neuron_model[1].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].model_label, "HH_O1");
	neuron_model[1].Initialize        = ModelInitialize_HH_O1;
	neuron_model[1].Advance           = ModelAdvance_HH_O1;
	n_params = 9;
	neuron_model[1].n_params          = 9;
	neuron_model[1].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[1].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[0], "Cm[nF]");
	neuron_model[1].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[1], "gL[uS]");
	neuron_model[1].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[2], "EL[mV]");
	neuron_model[1].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[3], "gNa_bar[uS]");
	neuron_model[1].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[4], "ENa[mV]");
	neuron_model[1].param_label[5]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[5], "gK_bar[uS]");
	neuron_model[1].param_label[6]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[6], "EK[mV]");
	neuron_model[1].param_label[7]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[7], "Temp[Celsius]");
	neuron_model[1].param_label[8]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].param_label[8], "VTraub[mV]");
	n_statevars = 3;
	neuron_model[1].n_statevars       = 3;
	neuron_model[1].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	neuron_model[1].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].statevar_label[0], "m[1]");
	neuron_model[1].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].statevar_label[1], "h[1]");
	neuron_model[1].statevar_label[2] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[1].statevar_label[2], "n[1]");

	// model_Izhikevich
	neuron_model[2].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].model_label, "Izhikevich");
	neuron_model[2].Initialize        = ModelInitialize_Izhikevich;
	neuron_model[2].Advance           = ModelAdvance_Izhikevich;
	n_params = 4;
	neuron_model[2].n_params          = 4;
	neuron_model[2].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[2].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].param_label[0], "a[1/ms]");
	neuron_model[2].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].param_label[1], "b[1]");
	neuron_model[2].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].param_label[2], "c[mV]");
	neuron_model[2].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].param_label[3], "d[mV]");
	n_statevars = 1;
	neuron_model[2].n_statevars       = 1;
	neuron_model[2].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	neuron_model[2].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[2].statevar_label[0], "u[mV]");

	// model_Izhikevich_O1
	neuron_model[3].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].model_label, "Izhikevich_O1");
	neuron_model[3].Initialize        = ModelInitialize_Izhikevich_O1;
	neuron_model[3].Advance           = ModelAdvance_Izhikevich_O1;
	n_params = 4;
	neuron_model[3].n_params          = 4;
	neuron_model[3].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[3].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].param_label[0], "a[1/ms]");
	neuron_model[3].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].param_label[1], "b[1]");
	neuron_model[3].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].param_label[2], "c[mV]");
	neuron_model[3].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].param_label[3], "d[mV]");
	n_statevars = 1;
	neuron_model[3].n_statevars       = 1;
	neuron_model[3].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	neuron_model[3].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[3].statevar_label[0], "u[mV]");

	// model_LIF
	neuron_model[4].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].model_label, "LIF");
	neuron_model[4].Initialize        = ModelInitialize_LIF;
	neuron_model[4].Advance           = ModelAdvance_LIF;
	n_params = 6;
	neuron_model[4].n_params          = 6;
	neuron_model[4].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[4].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[0], "Cm[nF]");
	neuron_model[4].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[1], "Rm[Mohm]");
	neuron_model[4].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[2], "Vrest[mV]");
	neuron_model[4].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[3], "Vthresh[mV]");
	neuron_model[4].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[4], "Vreset[mV]");
	neuron_model[4].param_label[5]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[4].param_label[5], "RefracP[ms]");
	n_statevars = 0;
	neuron_model[4].n_statevars       = 0;
	neuron_model[4].statevar_label    = NULL;

	// model_LIF_O1
	neuron_model[5].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].model_label, "LIF_O1");
	neuron_model[5].Initialize        = ModelInitialize_LIF_O1;
	neuron_model[5].Advance           = ModelAdvance_LIF_O1;
	n_params = 6;
	neuron_model[5].n_params          = 6;
	neuron_model[5].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[5].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[0], "Cm[nF]");
	neuron_model[5].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[1], "Rm[Mohm]");
	neuron_model[5].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[2], "Vrest[mV]");
	neuron_model[5].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[3], "Vthresh[mV]");
	neuron_model[5].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[4], "Vreset[mV]");
	neuron_model[5].param_label[5]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[5].param_label[5], "RefracP[ms]");
	n_statevars = 0;
	neuron_model[5].n_statevars       = 0;
	neuron_model[5].statevar_label    = NULL;

	// model_Pas
	neuron_model[6].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[6].model_label, "Pas");
	neuron_model[6].Initialize        = ModelInitialize_Pas;
	neuron_model[6].Advance           = ModelAdvance_Pas;
	n_params = 3;
	neuron_model[6].n_params          = 3;
	neuron_model[6].param_label       = malloc( n_params * sizeof( char * ) );
	neuron_model[6].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[6].param_label[0], "Cm[nF]");
	neuron_model[6].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[6].param_label[1], "g_pas[uS]");
	neuron_model[6].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( neuron_model[6].param_label[2], "E_pas[mV]");
	n_statevars = 0;
	neuron_model[6].n_statevars       = 0;
	neuron_model[6].statevar_label    = NULL;


	//TAKE CARE OF SYNAPSE MODELS
	//---------------------------

	// model_AMPA_NMDA
	synapse_model[0].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].model_label, "AMPA_NMDA");
	synapse_model[0].Initialize        = ModelInitialize_AMPA_NMDA;
	synapse_model[0].Activate          = ModelActivate_AMPA_NMDA;
	synapse_model[0].Advance           = ModelAdvance_AMPA_NMDA;
	n_params = 8;
	synapse_model[0].n_params          = 8;
	synapse_model[0].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[0].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[0], "g_max_AMPA[uS]");
	synapse_model[0].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[1], "g_max_NMDA[uS]");
	synapse_model[0].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[2], "E_syn[mV]");
	synapse_model[0].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[3], "AMPA_rise[ms]");
	synapse_model[0].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[4], "AMPA_decay[ms]");
	synapse_model[0].param_label[5]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[5], "NMDA_rise[ms]");
	synapse_model[0].param_label[6]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[6], "NMDA_decay[ms]");
	synapse_model[0].param_label[7]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].param_label[7], "Mgo[mM]");
	n_statevars = 6;
	synapse_model[0].n_statevars       = 6;
	synapse_model[0].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	synapse_model[0].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[0], "norm_AMPA[1]");
	synapse_model[0].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[1], "g_AMPA_A[1]");
	synapse_model[0].statevar_label[2] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[2], "g_AMPA_B[1]");
	synapse_model[0].statevar_label[3] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[3], "norm_NMDA[1]");
	synapse_model[0].statevar_label[4] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[4], "g_NMDA_A[1]");
	synapse_model[0].statevar_label[5] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[0].statevar_label[5], "g_NMDA_B[1]");

	// model_AlphaSyn
	synapse_model[1].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].model_label, "AlphaSyn");
	synapse_model[1].Initialize        = ModelInitialize_AlphaSyn;
	synapse_model[1].Activate          = ModelActivate_AlphaSyn;
	synapse_model[1].Advance           = ModelAdvance_AlphaSyn;
	n_params = 3;
	synapse_model[1].n_params          = 3;
	synapse_model[1].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[1].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].param_label[0], "g_max[uS]");
	synapse_model[1].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].param_label[1], "E_syn[mV]");
	synapse_model[1].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].param_label[2], "tau[ms]");
	n_statevars = 2;
	synapse_model[1].n_statevars       = 2;
	synapse_model[1].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	synapse_model[1].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].statevar_label[0], "g_syn[1]");
	synapse_model[1].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[1].statevar_label[1], "g_aux[1]");

	// model_Exp2Syn
	synapse_model[2].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].model_label, "Exp2Syn");
	synapse_model[2].Initialize        = ModelInitialize_Exp2Syn;
	synapse_model[2].Activate          = ModelActivate_Exp2Syn;
	synapse_model[2].Advance           = ModelAdvance_Exp2Syn;
	n_params = 4;
	synapse_model[2].n_params          = 4;
	synapse_model[2].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[2].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].param_label[0], "g_max[uS]");
	synapse_model[2].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].param_label[1], "E_syn[mV]");
	synapse_model[2].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].param_label[2], "tau_rise[ms]");
	synapse_model[2].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].param_label[3], "tau_decay[ms]");
	n_statevars = 3;
	synapse_model[2].n_statevars       = 3;
	synapse_model[2].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	synapse_model[2].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].statevar_label[0], "norm[1]");
	synapse_model[2].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].statevar_label[1], "g_syn_A[1]");
	synapse_model[2].statevar_label[2] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[2].statevar_label[2], "g_syn_B[1]");

	// model_ExpSyn
	synapse_model[3].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[3].model_label, "ExpSyn");
	synapse_model[3].Initialize        = ModelInitialize_ExpSyn;
	synapse_model[3].Activate          = ModelActivate_ExpSyn;
	synapse_model[3].Advance           = ModelAdvance_ExpSyn;
	n_params = 3;
	synapse_model[3].n_params          = 3;
	synapse_model[3].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[3].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[3].param_label[0], "g_step[uS]");
	synapse_model[3].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[3].param_label[1], "E_syn[mV]");
	synapse_model[3].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[3].param_label[2], "tau_syn[ms]");
	n_statevars = 1;
	synapse_model[3].n_statevars       = 1;
	synapse_model[3].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	synapse_model[3].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[3].statevar_label[0], "g_syn[S]");

	// model_IExpSyn
	synapse_model[4].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[4].model_label, "IExpSyn");
	synapse_model[4].Initialize        = ModelInitialize_IExpSyn;
	synapse_model[4].Activate          = ModelActivate_IExpSyn;
	synapse_model[4].Advance           = ModelAdvance_IExpSyn;
	n_params = 2;
	synapse_model[4].n_params          = 2;
	synapse_model[4].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[4].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[4].param_label[0], "I_max[nA]");
	synapse_model[4].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[4].param_label[1], "tau_decay[ms]");
	n_statevars = 0;
	synapse_model[4].n_statevars       = 0;
	synapse_model[4].statevar_label    = NULL;

	// model_ISyn
	synapse_model[5].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[5].model_label, "ISyn");
	synapse_model[5].Initialize        = ModelInitialize_ISyn;
	synapse_model[5].Activate          = ModelActivate_ISyn;
	synapse_model[5].Advance           = ModelAdvance_ISyn;
	n_params = 2;
	synapse_model[5].n_params          = 2;
	synapse_model[5].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[5].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[5].param_label[0], "I_max[nA]");
	synapse_model[5].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[5].param_label[1], "dur[ms]");
	n_statevars = 0;
	synapse_model[5].n_statevars       = 0;
	synapse_model[5].statevar_label    = NULL;

	// model_NMDA
	synapse_model[6].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].model_label, "NMDA");
	synapse_model[6].Initialize        = ModelInitialize_NMDA;
	synapse_model[6].Activate          = ModelActivate_NMDA;
	synapse_model[6].Advance           = ModelAdvance_NMDA;
	n_params = 5;
	synapse_model[6].n_params          = 5;
	synapse_model[6].param_label       = malloc( n_params * sizeof( char * ) );
	synapse_model[6].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].param_label[0], "g_max[uS]");
	synapse_model[6].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].param_label[1], "E_syn[mV]");
	synapse_model[6].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].param_label[2], "tau_rise[ms]");
	synapse_model[6].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].param_label[3], "tau_decay[ms]");
	synapse_model[6].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].param_label[4], "Mgo[mM]");
	n_statevars = 3;
	synapse_model[6].n_statevars       = 3;
	synapse_model[6].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	synapse_model[6].statevar_label[0] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].statevar_label[0], "norm[1]");
	synapse_model[6].statevar_label[1] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].statevar_label[1], "g_syn_A[1]");
	synapse_model[6].statevar_label[2] = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( synapse_model[6].statevar_label[2], "g_syn_B[1]");


	//TAKE CARE OF PLASTICITY MODELS
	//------------------------------

	// model_Hebb
	plasticity_model[0].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[0].model_label, "Hebb");
	plasticity_model[0].Initialize        = ModelInitialize_Hebb;
	plasticity_model[0].Activate          = ModelActivate_Hebb;
	n_params = 3;
	plasticity_model[0].n_params          = 3;
	plasticity_model[0].param_label       = malloc( n_params * sizeof( char * ) );
	plasticity_model[0].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[0].param_label[0], "w_max[1]");
	plasticity_model[0].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[0].param_label[1], "delta_w[1]");
	plasticity_model[0].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[0].param_label[2], "timewindow[ms]");
	n_statevars = 0;
	plasticity_model[0].n_statevars       = 0;
	plasticity_model[0].statevar_label    = NULL;

	// model_STDP
	plasticity_model[1].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].model_label, "STDP");
	plasticity_model[1].Initialize        = ModelInitialize_STDP;
	plasticity_model[1].Activate          = ModelActivate_STDP;
	n_params = 5;
	plasticity_model[1].n_params          = 5;
	plasticity_model[1].param_label       = malloc( n_params * sizeof( char * ) );
	plasticity_model[1].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].param_label[0], "tau_pre[ms]");
	plasticity_model[1].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].param_label[1], "tau_post[ms]");
	plasticity_model[1].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].param_label[2], "D_pre[1]");
	plasticity_model[1].param_label[3]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].param_label[3], "D_post[1]");
	plasticity_model[1].param_label[4]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[1].param_label[4], "w_max[1]");
	n_statevars = 0;
	plasticity_model[1].n_statevars       = 0;
	plasticity_model[1].statevar_label    = NULL;

	// model_STP
	plasticity_model[2].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].model_label, "STP");
	plasticity_model[2].Initialize        = ModelInitialize_STP;
	plasticity_model[2].Activate          = ModelActivate_STP;
	n_params = 3;
	plasticity_model[2].n_params          = 3;
	plasticity_model[2].param_label       = malloc( n_params * sizeof( char * ) );
	plasticity_model[2].param_label[0]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].param_label[0], "U1[1]");
	plasticity_model[2].param_label[1]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].param_label[1], "tau_fac[ms]");
	plasticity_model[2].param_label[2]    = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].param_label[2], "tau_rec[ms]");
	n_statevars = 2;
	plasticity_model[2].n_statevars       = 2;
	plasticity_model[2].statevar_label    = malloc( n_statevars * sizeof( char * ) );
	plasticity_model[2].statevar_label[0]  = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].statevar_label[0], "Use[1]");
	plasticity_model[2].statevar_label[1]  = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[2].statevar_label[1], "P[1]");

	// model_Static
	plasticity_model[3].model_label       = malloc( MAX_STRING_SIZE * sizeof( char ) );
	strcpy( plasticity_model[3].model_label, "Static");
	plasticity_model[3].Initialize        = ModelInitialize_Static;
	plasticity_model[3].Activate          = ModelActivate_Static;
	n_params = 0;
	plasticity_model[3].n_params          = 0;
	plasticity_model[3].param_label       = malloc( n_params * sizeof( char * ) );
	n_statevars = 0;
	plasticity_model[3].n_statevars       = 0;
	plasticity_model[3].statevar_label    = NULL;


	return;
}



//------------------------------------------------------------------------
// Get appropriate neuron model structure from the neuron model string
struct MODEL_DYNAMICS_NEURON* GetNeuronModelFromString( char *modelname )
{
	if( strcmp("HH", modelname) == 0 ) {
		return &neuron_model[0];
	}

	if( strcmp("HH_O1", modelname) == 0 ) {
		return &neuron_model[1];
	}

	if( strcmp("Izhikevich", modelname) == 0 ) {
		return &neuron_model[2];
	}

	if( strcmp("Izhikevich_O1", modelname) == 0 ) {
		return &neuron_model[3];
	}

	if( strcmp("LIF", modelname) == 0 ) {
		return &neuron_model[4];
	}

	if( strcmp("LIF_O1", modelname) == 0 ) {
		return &neuron_model[5];
	}

	if( strcmp("Pas", modelname) == 0 ) {
		return &neuron_model[6];
	}

	// it's not good at all if you arrive here empty handed...
	printf("\n\nERROR - It was not possible to associate a neuron (fdomain) modelname with the appropriate set of function pointers\nThe error occurred with the modelname = %s\n\nIf you added new models you need to run again NeuralSyns instalation script. Check also if the libraries in the 'dynamics' folder have errors\n", modelname);
	return NULL;
}



//------------------------------------------------------------------------
// Get appropriate synapse model structure from the synapse model string
struct MODEL_DYNAMICS_SYNAPSE* GetSynapseModelFromString( char *modelname )
{
	if( strcmp("AMPA_NMDA", modelname) == 0 ) {
		return &synapse_model[0];
	}

	if( strcmp("AlphaSyn", modelname) == 0 ) {
		return &synapse_model[1];
	}

	if( strcmp("Exp2Syn", modelname) == 0 ) {
		return &synapse_model[2];
	}

	if( strcmp("ExpSyn", modelname) == 0 ) {
		return &synapse_model[3];
	}

	if( strcmp("IExpSyn", modelname) == 0 ) {
		return &synapse_model[4];
	}

	if( strcmp("ISyn", modelname) == 0 ) {
		return &synapse_model[5];
	}

	if( strcmp("NMDA", modelname) == 0 ) {
		return &synapse_model[6];
	}

	// it's not good at all if you arrive here empty handed...
	printf("\n\nERROR - It was not possible to associate a synapse modelname with the appropriate set of function pointers\nThe error occurred with the modelname = %s\n\nIf you added new models you need to run again NeuralSyns instalation script. Check also if the libraries in the 'dynamics' folder have errors\n", modelname);
	return NULL;
}



//------------------------------------------------------------------------
// Get appropriate plasticty model structure from the plasticity model string
struct MODEL_DYNAMICS_PLASTICITY* GetPlasticityModelFromString( char *modelname )
{
	if( strcmp("Hebb", modelname) == 0 ) {
		return &plasticity_model[0];
	}

	if( strcmp("STDP", modelname) == 0 ) {
		return &plasticity_model[1];
	}

	if( strcmp("STP", modelname) == 0 ) {
		return &plasticity_model[2];
	}

	if( strcmp("Static", modelname) == 0 ) {
		return &plasticity_model[3];
	}

	// it's not good at all if you arrive here empty handed...
	printf("\n\nERROR - It was not possible to associate a plasticity modelname with the appropriate set of function pointers\nThe error occurred with the modelname = %s\n\nIf you added new models you need to run again NeuralSyns instalation script. Check also if the libraries in the 'dynamics' folder have errors\n", modelname);
	return NULL;
}
